version: '3'

######### Services ###################################

services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/laravel
    working_dir: /var/www/laravel
    depends_on:
      - mysql
    environment:
      - "DB_PORT={$DB_PORT}"
      - "DB_HOST=mysql"

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
        MYSQL_ROOT_PASSWORD: laravel
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
######### Volumes ###################################

volumes:
  mysql-volume:
